language: scala

cache:
  directories:
    - $HOME/.sbt/launchers

jdk:
  - oraclejdk8

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - ./travis.sh

env:
  global:
  - secure: h4pMOc+xQxgnoxlWzU9jGkd2i26VVOhcMydDQ1unIVfpcRCWz6rj5KWQutRQ4vuDg1+eCwUMXeG9HjOptQXFlRonOprGh/TyhjqTvukT6jwi76UdMQk9F412e1cV21t67FEdil96CTyxtd385Cv1ZfaxjmGdkqG8Jlu7/qJYCI8=
  - secure: XFwrfgjssMLrg4rNrr1fnq0tdXMAIXGhGwaRQzzgiwACkTNuQaIdlD0DoEt42ClWxpfkxqYneihtVm2c2jJHyBB4y1AjXCKuINdH2TUpzj7Ix09O6MedeuW39pNs2vLttUHpREWjGt/ObA6pZoDELEmQyhAszDscHc/9IIGq/NE=
